### ISSUE TITLE
fireWithDefaultMethod() function definition is missing.

### ISSUE THREAD

**Issue by ronakkhunt** [metalshan/Smartjax#3]
I think fireWithDefaultMethod() definition is missing. when user tries to call without specifying type.

**Comment by metalshan** [comment]
Hi,

Thanks for notifying. Method type doesn't play a role to make unique store id, as it's not possible to make two different calls (suppose POST and PUT) in the same url and same data. That's why there's no meaning to treat things differently. Hence the method has been removed previously and now I've removed that check too.
